# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# laguna-s-2.1: OpenAI-compatible Chat Completions.
# Supply the endpoint's model identifier with --model; see README.md.
agent:
  step_limit: 350
environment:
  timeout: 120
model:
  model_class: litellm
  model_kwargs:
    max_tokens: 131072
    extra_body:
      reasoning_effort: max
